DROP DATABASE IF EXISTS Tienda;
CREATE DATABASE IF NOT EXISTS Tienda;
USE Tienda;

CREATE TABLE cliente(
    ID INT UNSIGNED PRIMARY KEY,
    Nombre VARCHAR(30) NOT NULL,
    Direccion VARCHAR(80) NOT NULL
);

CREATE TABLE producto(
    ID INT UNSIGNED PRIMARY KEY,
    Precio INT UNSIGNED NOT NULL,
    Nombre VARCHAR(30) NOT NULL
);

CREATE TABLE producto_comprado(
    ID_Comprado INT UNSIGNED PRIMARY KEY,
    ID_producto INT UNSIGNED NOT NULL,
    ID_Cliente INT UNSIGNED NOT NULL,
    FOREIGN KEY(ID_producto) REFERENCES producto(ID),
    FOREIGN KEY(ID_Cliente) REFERENCES cliente(ID)
);
